import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "EL AZZOUZI HASSAN | PORTFOLIO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <header>
            <nav>
              <ul>
                <li><Link href="/">Accueil</Link></li>
                <li><Link href="/about">À propos</Link></li>
                <li><Link href="/skills">Compétences</Link></li>
                <li><Link href="/projects">Projets</Link></li>
              </ul>
            </nav>
          </header>
          <main>
            {children}
          </main>
          <footer>
            <p>&copy; 2024 Mon Portfolio</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
